version: '3.8'

services:
  ocr-annotation-tool:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount data directories to persist annotations
      - ./New_ocr:/app/New_ocr
      - ./Old_ocr:/app/Old_ocr
      - ./images:/app/images
    environment:
      - NODE_ENV=production
    restart: unless-stopped
